### ISSUE TITLE
Default wallet is SR25119 while Polkadot.js is ED25519

### ISSUE THREAD

**Issue by JesseAbram** [plugblockchain/wallet.js#1]
Hey, was going through your documentation. I noticed that the default wallet type is SR25119. Currently as of version    "@polkadot/api": "^0.79.1" the default type is ED25519. Just thought I would bring it to your attention. Not sure if this will be changed soon or not (probably Jaco would know that)

**Comment by ianhe8x** [comment]
substrate support both SR25119 and ED25519, and its our decision to make SR25119 as default for this lib. Users are still allow to create keyring of ED25519.
similar interface as `@polkadot/keyring`
